apiVersion: v1
entries:
  course-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-12-15T04:33:59.546891447Z"
    description: backend course-service
    digest: 5b393fea598f92c5a87d9d021f3d32506c9c992de7ae8a4986ae1e6087fd0c75
    name: course-service
    type: application
    urls:
    - https://meland-inc.github.io/charts/charts/course-service-0.1.0-debugdebugdebug.tgz
    version: 0.1.0-debugdebugdebug
generated: "2021-12-15T04:33:59.546295855Z"
